### ISSUE TITLE
Rename repo to zammad-api-client-ruby

### ISSUE THREAD

**Issue by monotek** [zammad/zammad-api-client-ruby#1]
Just to have consistent naming in all repos. 

PHP API already is: zammad-api-client-php

**Comment by martini** [comment]
@jepf anything against changing it at https://github.com/zammad/zammad-api-client-php to underscores?

**Comment by monotek** [comment]
Would work too but then the other repos which i'd like to rename (docker https://github.com/zammad/docker/issues/5 & vagrant https://github.com/zammad/vagrant/issues/3) should have underscores to.

**Comment by mbeijen** [comment]
If you rename the repository using Github Settings item, you'll get auto
forwarding of the old urls.

https://help.github.com/articles/renaming-a-repository/

Op zaterdag 29 oktober 2016 heeft André Bauer notifications@github.com
het volgende geschreven:
