### ISSUE TITLE
Add support for 'X-On-Behalf-Of'-Header.

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-api-client-ruby#4]
Hi,
there is a new feature which should get supported in the zammad apis:

issue:
https://github.com/zammad/zammad/issues/1805

documentation:
https://docs.zammad.org/en/latest/api-intro.html#example-curl-request-on-behalf-of-a-different-user

Best regards,
Rolf

**Comment by thorsteneckel** [comment]
This is available with the new 1.0.4 release as [described here](https://github.com/zammad/zammad-api-client-ruby#perform-actions-on-behalf-of-other-user).
