### ISSUE TITLE
logger 1.2.8 no longer available

### ISSUE THREAD

**Issue by cvshepherd** [zammad/zammad-api-client-ruby#5]
just got an error message from bundle because of this. turns out 1.2.8 was recently janked, as can be seen here:

https://rubygems.org/gems/logger/versions/1.2.8

is this gem actually still necessary?

**Comment by thorsteneckel** [comment]
Hi @cvshepherd - thanks a lot for raising the awareness. I removed the dependency (because logger is part of the Ruby core lib), created and published the new 1.0.5 release. Closing now.
