### ISSUE TITLE
Farady Dependency conflict with sentry-raven

### ISSUE THREAD

**Issue by bh8ur8js** [zammad/zammad-api-client-ruby#9]
when running bundle install on my rails project, I got the following.

```
Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 1.0.1)

  In Gemfile:
    sentry-raven was resolved to 3.0.0, which depends on
      faraday (>= 1.0)

    zammad_api was resolved to 1.0.5, which depends on
      faraday (~> 0.9)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Running bundle update works however downgrades sentry-raven to 2.13.0. It is a Devise dependancy so very important from a security perspective to be running the latest version.

After 

`gem install zammad-api
`
I updated, locally, the zammad_api-1.0.5.gemspec version for faraday to 1.0.1 and everything seems to work. 

I would appreciate your thoughts about how I could make this change in production in Heroku? Or whether this can be update in the gem?

**Comment by thorsteneckel** [comment]
Hey @bh8ur8js - this should be fixed with the commit above. I just released version 1.0.6 of the `zammad_api` gem. Let me know if it works for you.
